[font]
size = 9.6

normal = { family = "CourierPrimeNerdFont" }
bold = { family = "CourierPrimeNerdFont" }
italic = { family = "CourierPrimeNerdFont" }
bold_italic = { family = "CourierPrimeNerdFont" }

[window]
padding = { x = 2, y = 2 }

[colors]
primary.background = "#000000"
cursor.text = "#000000"
cursor.cursor = "#1ff21f"
